### ISSUE TITLE
Logged In As ???

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic-lab-issues#1]
After logging in, name is not showing

(Mac, Alpha 13)

![image](https://cloud.githubusercontent.com/assets/1685242/8759535/9ed30a28-2cbb-11e5-8b03-fb56b2c278c0.png)

**Comment by jbavari** [comment]
This should be corrected in the next release.

Thanks for reporting!

**Comment by jbavari** [comment]
This is out in alpha 14.
