### ISSUE TITLE
Old plugin names for camera and contacts

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#10]
It looks like when you add Camera and Contacts you add the old org.apache.etc names instead of cordova-plugin-\* names.

**Comment by jbavari** [comment]
Yep, started this long ago before those plugins changed. I'll get those updated.

**Comment by jbavari** [comment]
Raymond - whats the best way that you know of to get a list of the apache supported plugins?

I used to hit: `http://plugins.cordova.io/_list/search/search?startkey=%22cordova-plugin%22&endkey=%22cordova-pluginZZZZZZZZZZZZZZ%22&limit=50`

Not sure if thats what I want anymore.

**Comment by cfjedimaster** [comment]
You mean the "official" list or all plugins? If you mean the official list, I'd hard code it. They don't change that list very often.

**Comment by jbavari** [comment]
The official list. You're right, i'll just manually modify it for now.

**Comment by jbavari** [comment]
This is out in alpha 14.
