### ISSUE TITLE
Consider keeping notifications longer

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#11]
I mentioned this in the bug about adding Android, but messages at the bottom of the screen auto dismiss, and if you aren't paying attention, you can miss them. If you are ADD like me and decide to do 5 things at once, you may miss that an operation successfully completed (or threw an error). That's my fault of course, but I'd consider making status messages, the final one, persist at the bottom until dismissed by the user.

**Comment by mdridley** [comment]
I agree with this one. Would be nice to maybe have a way to review the message logs, so that you can copy & paste for bug reporting or for future Google searches and such.

**Comment by jbavari** [comment]
Roger - for starters we just popped up messages. It's a pretty loose notification system and needs some work.

You're right @mdridley - we should be showing some sort of notifications popup to review the notifications. Going to address that this week.

**Comment by jbavari** [comment]
This has been bumped up in alpha 14. Thanks again.
