### ISSUE TITLE
Release/Updates

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic-lab-issues#13]
Would be nice to be able to check for updates automatically. Perfect world would be like Android Studio where you could choose your channel (Alpha, Beta, Dev, Release).

**Comment by jbavari** [comment]
That is in the works. We are still in the early stages of building this. :8ball:

**Comment by mdridley** [comment]
Figured, until then, is there a way to know when a new version is ready to download and install? (Are you just going to send an email out or ?)

**Comment by jbavari** [comment]
I'll get some sort of system in the next release. For now, I will email you until that is done.

**Comment by jbavari** [comment]
This is now available in alpha 14.
