### ISSUE TITLE
Importing an existing project fails

### ISSUE THREAD

**Issue by rossmartin** [driftyco/ionic-lab-issues#14]
I have an existing Ionic app that I'm trying to import but it fails silently.  According to the dev console it appears to be because of a missing `package.json` in the root of the project) -

![image](https://cloud.githubusercontent.com/assets/2498502/8854805/6f58f83c-3127-11e5-97ad-a104c914660c.png)

This project was initially created with an older version of the Cordova CLI so maybe that is why the root `package.json` is missing.  I did update to the latest version of the Cordova CLI and did a `cordova platform update` for both ios/android but it won't import and the `package.json` file is still missing.

I'm using OS X Yosemite.

**Comment by jbavari** [comment]
I'm looking into this one now. Thanks for reporting Ross!

**Comment by jbavari** [comment]
@rossmartin I've now got the status bar showing that it does not have a package.json file.

However, I only need the package.json file mainly to look up the project name. I can also look up the project name from the ionic.project file.

Did you older app there have an ionic.project file?

Trying to think of the best way to handle this, would love some feedback. What do you think, perhaps show the error message, instructions to run 'npm init' or something of the like?

**Comment by rossmartin** [comment]
Thanks.  My older app didn't have an ionic.project file.  I think showing a message with instructions on how to fix would be perfect.  Will `npm init` fix the issue?

**Comment by jbavari** [comment]
@rossmartin Yes, the instructions specify to run `npm init`. New alpha should be out today.

**Comment by jbavari** [comment]
Fixed in alpha 16.
