### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#15]
Add em. I have a icon in the upper right side (to the left of the settings gear) and I can't tell what it is. I assumed I could mouse over and wait for a tooltip, but none show up.

**Comment by cfjedimaster** [comment]
So I clicked, it opened up a bottom panel. I honestly thought it was a folder icon and it would open the folder for the app.

**Comment by bensperry** [comment]
Agreed. I'd like to add them as well. That icon will be switched soon, it's a filler until we polish up that experience.

**Comment by jbavari** [comment]
I've added some in for the logs and settings icons.

**Comment by jbavari** [comment]
Added in alpha 16.
