### ISSUE TITLE
Log panel right side icons are blocked a bit

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#16]
In the screen shot below, the X icon is partially blocked:

![image](https://cloud.githubusercontent.com/assets/393660/8858436/0cdf9466-313d-11e5-893f-858da06f56b5.png)

**Comment by jbavari** [comment]
Interesting, I dont have those scroll bars. I wonder if theres a way to detect if they show?

Just going to bump the right css property.

**Comment by cfjedimaster** [comment]
I'm sure there is a way of handling it in CSS. Much like how centering
things is easy in CSS. And layout.

Good luck!

On Thu, Jul 23, 2015 at 5:13 PM, Josh Bavari notifications@github.com
wrote:

> Interesting, I dont have those scroll bars. I wonder if theres a way to
> detect if they show?
> 
> Just going to bump the right css property.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/driftyco/ionic-lab-issues/issues/16#issuecomment-124252598
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by jbavari** [comment]
Fixed in alpha 16.
