### ISSUE TITLE
Request: Create New Folder Option

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic-lab-issues#2]
When creating a new app, would be nice to see a "create new app folder" option/checkbox. Currently not clear if it will or not.

**Comment by jbavari** [comment]
How do mean precisely? Do this on the folder/directory 'Browse' button is hit? Or within the app itself?

**Comment by mdridley** [comment]
I think either would work. The app itself would be fine, just having it right below where the directory is shown that was chosen.

**Comment by jbavari** [comment]
@mdridley For now, we are just going to stick with the default 'New Folder' button that the `Select File` dialog provides. (Near the bottom of this screenshot)
<img width="995" alt="screen shot 2015-07-31 at 9 23 05 am" src="https://cloud.githubusercontent.com/assets/1414692/9010704/cc9ae192-3765-11e5-9223-92ff91d692d0.png">

**Comment by jbavari** [comment]
Closing for now.
