### ISSUE TITLE
Checking plugins messes up their order

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#21]
I was in the Plugins area enabling multiple plugins at once. While I clicked, I saw the order of plugins change, kind of randomly. If I had to guess, I'd say they were trying to sort by checked. I would not sort them at all, or at minimum, wait to sort till you leave that tab and return. 

Personally I'd vote for keeping them in alpha order.

**Comment by cfjedimaster** [comment]
In testing some clicks to remove, not even going very fast, I actually clicked the wrong item because it sorted right before I clicked.

**Comment by jbavari** [comment]
Roger, bad user interaction. Changing.

**Comment by jbavari** [comment]
Fixed, should be available in new alpha today.

**Comment by jbavari** [comment]
Fixed in alpha 16.
