### ISSUE TITLE
ios build failed, but no log

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#29]
I just tried to build for iOS. It immediately failed, and I got the message at the bottom (which imo still goes away too quickly), but nothing new was shown in the log window. I believe this is the same message I saw before:

Generating config.xml from defaults for platform "ios"
Calling plugman.prepare for platform "ios"
Preparing ios project
Processing configuration changes for plugins.
Iterating over installed plugins:
Writing out cordova_plugins.js...

**Comment by cfjedimaster** [comment]
As an FYI, I tried a virgin project, and I can't even install ios.

Generating config.xml from defaults for platform "ios"
Calling plugman.prepare for platform "ios"
Preparing ios project
Processing configuration changes for plugins.
Iterating over installed plugins:
Writing out cordova_plugins.js...
Creating Ionic app in folder Select path to create app based on sidemenu project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
Downloading: https://github.com/driftyco/ionic-starter-sidemenu/archive/master.zip
Error
Updated the hooks directory to have execute permissions
Update Config.xml
Initializing cordova project
Adding in iOS application by default
There was an error finalizing the package.json file.
No version supplied. Retrieving version from config.xml...

**Comment by cfjedimaster** [comment]
Ouch. So, in this virgin project, I installed Android and it worked ok. I then did Build, and I got: "You are trying to build iOS and it is not installed."

So the previous attempt to add ios got part way through I believe.

**Comment by jbavari** [comment]
Roger, I'll look into it.

**Comment by cfjedimaster** [comment]
Adding more info on this.

I made yet another virgin project, and this one actually got iOS. It seemed ok. I even did a build.
I then did emulate, and it failed:

ERROR running one or more of the platforms: Error: ENOENT: no such file or directory, open '/Users/raymondcamden/Desktop/trash/platforms/ios/HelloCordova/config.xml'

And then build stopped working too.

**Comment by jbavari** [comment]
Build logs are now available.
