### ISSUE TITLE
Old Plug-In References

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic-lab-issues#3]
Seeing warnings in logs from old references to plug-ins:

![image](https://cloud.githubusercontent.com/assets/1685242/8759612/89a2709c-2cbd-11e5-8222-d4c8af39e207.png)

Also, on second app (deleted the first), The checked plug-ins disappear after losing focus. Did not remember that happening the first time. Was not sure if this was expected or not.

**Comment by jbavari** [comment]
This is out in alpha 14.
