### ISSUE TITLE
Checkboxes in app list

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#30]
Ok, I'm the last person to comment on design, but what's up with the checkboxes in the app list? They don't actually do anything as far as I can tell.

![image](https://cloud.githubusercontent.com/assets/393660/8969878/afaae5d8-360b-11e5-8a88-5feac82b03ae.png)

**Comment by jbavari** [comment]
For now, those are placeholders. We are planning to have those be the app icon of the application, once the user uploads one.

This is still pending integrations with ionic resources, as well.

**Comment by cfjedimaster** [comment]
Cool. Which leads me to an idea...

**Comment by bensperry** [comment]
Yes?

**Comment by cfjedimaster** [comment]
Sorry, I posted it as a new issue. :)

**Comment by jbavari** [comment]
@bensperry see #34

**Comment by jbavari** [comment]
We updated the icon to have the default ionic resources icon. Will be available in next release.
