### ISSUE TITLE
Issue when installing plugins too quickly

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#33]
If you try to install plugins too quickly, and I recognize that's a bit vague. I was clicking along the list about 1 every 1/2 second or so. Not _super_ fast, but I didn't wait for them to complete. Anyway, things didn't quite work right. I can make a video, but it seemed like the app got confused and tried to remove plugins I was trying to add. 

Yeah, I just reproduced this easily - just click 3 plugins in a row w/o waiting. None seem to install and you get an error.

**Comment by cfjedimaster** [comment]
Wow, now I can't install plugins at all on this project. So when it messes up, it breaks something at the project level.

**Comment by jbavari** [comment]
I'll have to say, integrating with the cordova-lib has been a pain. One that I'm not too happy with how the results turned out. It seems like everytime I patch something to fix, something else goes bonkers.

I'll look into this.

**Comment by cfjedimaster** [comment]
Ok, so I think we either have two issues here, or it is simply one issue related to the other bug I reported on iOS not installing and breaking the app. I see errors in console that it is trying to copy stuff for ios, but obviously my project doesn't support iso now due to the issues I reported elsewhere. 

Just to repeat - this may be two separate issues. I'm going to try again in a new project where I don't touch ios.

**Comment by cfjedimaster** [comment]
Not to make things more confusing, but on another virgin project, ios worked. So... ok. I tried my 'rapid click' and it worked fine. I think you can maybe close this as it's an issue with platform install leaving behind crap that breaks the project. (If that makes sense.)

**Comment by jbavari** [comment]
Yea, I think I've found that bug you've had, and it looks like some remnants of the 'adding platform'.

Still going to look into this, really want this stable by friday.

**Comment by jbavari** [comment]
This should be fixed.
