### ISSUE TITLE
Scroll to Bottom on Logs

### ISSUE THREAD

**Issue by mdridley** [driftyco/ionic-lab-issues#38]
When you open the logs for the first time it is at the top, scrolled to the bottom would seem to be a better approach.

**Comment by jbavari** [comment]
Good suggestion.

This should be in there. There will also need to be some kind of scroll lock to avoid scrolling while a user is examining the logs.

Kind of like this JSFiddle:

http://jsfiddle.net/nT75k/2/

**Comment by mdridley** [comment]
Yep, that would be perfect!

**Comment by jbavari** [comment]
Available in latest beta.
