### ISSUE TITLE
Able to clear local storage

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ionic-lab-issues#49]
I'd like functionality similar to `window.localStorage.clear()` in the browser. Thanks :)

**Comment by jbavari** [comment]
@sean-hill What would be the use case for this? Just to clear out the apps as stored in local storage?

Currently as a work around, you could clear the localStorage via console (open dev console, run command).

**Comment by sean-hill** [comment]
Honestly @jbavari, I can't remember why. I was testing it out and saw that it would be nice to have, but I can't remember why! If I do I'll open another ticket.

**Comment by jbavari** [comment]
Cool - sounds good. Right now if you click the 'x' on the app, it will remove it from local storage. 

If you think of it, please fill me in. Might be a nice way to reset the users application state, though!

**Comment by sean-hill** [comment]
@jbavari !!! That's exactly it. I use local storage to store user data such as an auth token, and what steps they've completed in my app. It'd be handy to clear that via the Ionic Lab app, and not just in my browser.
