### ISSUE TITLE
Logs too small to use

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#6]
This is how Logs render for me:

![image](https://cloud.githubusercontent.com/assets/393660/8761845/21afe734-2d2c-11e5-8e99-48f6fee4fff6.png)

I see no way to resize it and there is no way in heck I'm going to read it like that. :)

**Comment by cfjedimaster** [comment]
Related - even using the Plugin view it is a bit tight.

**Comment by jbavari** [comment]
Yep, getting some wires together to improve the logging system. cc @bensperry

**Comment by jbavari** [comment]
This is out in alpha 14.
