### ISSUE TITLE
Error installing Android

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#7]
I tried to install Android on a project and got an error. It auto dismissed (which is a mistake, if I had looked away I would not have seen it!), and I see no way of figuring out _what_ went wrong. It may be in the logs, but as the logs are hard to read, I'm not sure.

**Comment by cfjedimaster** [comment]
On a new project, I also got an error installing iOS. So maybe platform adding is broken in general.

**Comment by jbavari** [comment]
Could you try seeing if any output comes through on the dev console? Hit CMD+ALT+I.

**Comment by cfjedimaster** [comment]
For the comment on page 20, I disagreed and said why, and if you want to
continue that via email (may be easier than sending a doc back and forth),
I'd be cool with that.

On Mon, Jul 20, 2015 at 5:19 PM, Josh Bavari <notifications@github.com>
wrote:

> Could you try seeing if any output comes through on the dev console? Hit
> CMD+ALT+I.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-lab-issues/issues/7#issuecomment-123069725>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
Oops, I repied to the wrong email in Gmail. Hope I can delete it...

**Comment by cfjedimaster** [comment]
Sigh - so I test tonight and it works.

**Comment by cfjedimaster** [comment]
Ditto for ios.

**Comment by cfjedimaster** [comment]
cmd-alt-i eh - is this a nw.js app? :)

**Comment by cfjedimaster** [comment]
Ah, Electron. Digging into the source now. :)

**Comment by jbavari** [comment]
Yes, it's an electron app. Enjoy.

**Comment by jbavari** [comment]
Closing, please reopen if an issue in alpha 14.

**Comment by ryanmaclean** [comment]
### "Error Installing Android Platform"

Can report that this is back - brand new install of Ionic Lab on Windows 10, running either as normal user or as administrator. It appears that Ionic lab is looking for node, which is fine - maybe pop up an error stating that it's required on failure?

Scrubbed log from ctl+alt+i:

```
CordovaError: There was an error adding the platform:Error: cmd: Command failed with exit code 1 Error output:
'node' is not recognized as an internal or external command,
operable program or batch file.
    at C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\ionic-cordova-lib\src\cordova\platform.js:219:35
    at _rejected (C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:797:24)
    at C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:741:41)
    at C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:557:44
    at flush (C:\Users\string\AppData\Local\IonicLab\app-1.0.0\resources\app.asar\node_modules\ionic-app-lib\node_modules\q\q.js:108:17)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

**Comment by imuhammadarsalan** [comment]
i am using ionic lab desktop version & i am getting the error.
No version supplied. Retrieving version from config.xml...
What is the problem ?

**Comment by rojagit** [comment]
I just downloaded the Windows version today and I am getting this ridiculous error, Don't these guys even test their software before releasing it to public ?? How will we have confidence in anything they do at this rate ?

**Comment by rojagit** [comment]
I found the reason for this to be that labs depends on a clean CLI install, so go through whatever the CLI startup until cordova is, and then install android on an app works from the lab.

**Comment by rohitjaysankar** [comment]
I tried to install android on a project .It's not showing any error but its not getting installed.
