### ISSUE TITLE
Creating is slow

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#8]
Yeah yeah, kind of a nit pick, but making an app takes about 2 minutes. I'd say maybe 2-3X longer than the CLI.

**Comment by jbavari** [comment]
I added the start information in the logging. You're right, it does seem to take longer than normal. I'm investigating now.

**Comment by jbavari** [comment]
Added logging for start. If its still slow, please reopen. This is out in alpha 14.
