### ISSUE TITLE
Add a link to open folder

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-lab-issues#9]
Add a quick way to open the folder containing the project.

**Comment by jbavari** [comment]
This is available from the File menu. I was using the opn module to do this with default OS (finder or Windows Explorer), Sublime Text or Atom.

There was a change with the opn module and I had to update with the change.

Will be available in Alpha 14.

**Comment by cfjedimaster** [comment]
Sorry, to be clear, are you saying you will add the option to open the
folder? I do see open in sublime and atom (why not Visual Studio Code? :)
but I do not see an existing option to open the folder.

On Mon, Jul 20, 2015 at 9:06 AM, Josh Bavari notifications@github.com
wrote:

> This is available from the File menu. I was using the opn module to do
> this with default OS (finder or Windows Explorer), Sublime Text or Atom.
> 
> There was a change with the opn module and I had to update with the change.
> 
> Will be available in Alpha 14.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/driftyco/ionic-lab-issues/issues/9#issuecomment-122895983
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by jbavari** [comment]
Open the folder has been added.

Are you using Windows or Mac?

**Comment by cfjedimaster** [comment]
Mac

On Mon, Jul 20, 2015 at 9:13 AM, Josh Bavari notifications@github.com
wrote:

> Open the folder has been added.
> 
> Are you using Windows or Mac?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/driftyco/ionic-lab-issues/issues/9#issuecomment-122898546
> .

## 

# 

Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by jbavari** [comment]
I really would like to have the GUI check which applications are available before just showing all.

For now, I will show all. That being said, I have a flag in there, windows users see different items than Mac users do. Windows users will see Visual Studio regardless.

I'll go ahead and add Visual Studio Code to the list for Mac.

**Comment by jbavari** [comment]
This should be out in next release.

**Comment by jbavari** [comment]
This is out in alpha 14.
